services:
  - type: web
    name: rag-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python download_model.py
    startCommand: gunicorn main:app -w 1 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CHROMA_TENANT
        sync: false
      - key: CHROMA_DATABASE
        sync: false
      - key: CHROMA_API_KEY
        sync: false
      - key: OLLAMA_URL
        sync: false
